### ISSUE TITLE
Question: mRNA counts in LinearCount file 

### ISSUE THREAD

**Issue by knuppd** [dieterich-lab/DCC#61]
Hi Dieterich-lab,

Just a quick question - Are the Chimeric.Junction.out counts in the LinearCount file the raw counts for the host-mRNA at the location of the circExons? I.e. if you have a 2-exon circRNA and the chimeric.junction.out counts are 200,300,250 for your 3 biological replicates, do these counts only reflect the linear reads aligning to the 2 exons of the circRNA? 

Thanks!

**Comment by tjakobi** [comment]
Hi @knuppd,

the linear counts are counted for the region of the circRNA candidate (i.e. the region defined by the back splice junction) and is line-by-line paired between circRNA and linear counts. 

Given your example, the LinearCount file would include the read counts for the region of the two exons. In theory this may also contain reads from the circularized exons - but since we cannot distinguish between those and "normal" linear reads, all non-junction reads are counted as linear reads.

Cheers,
Tobias
