### ISSUE TITLE
read support for oRNA candidates

### ISSUE THREAD

**Issue by harperfauni** [dieterich-lab/DCC#75]
Hello,

I was just wondering if the read support for the circular RNA candidates are 0-based or 1-based coordinates. It seems that the read support are obtained from 1-based coordinates while other oRNA discovery tools such as CircExplorer2 and circRNA_finder are 0-based.

My question: Is it possible to obtain read support from 0-based coordinates?

Thanks!

Best,

Harper

**Comment by tjakobi** [comment]
Hi @harperfauni,

DCC is based on output from the STAR read mapper. The positions that are contained the chimeric output files are 1-based, therefore DCC in general is also 1-based.

However, if you require 0-based numbers, you may use `sed` or similar command line tools to convert the positions accordingly.

Cheers,
Tobias

**Comment by harperfauni** [comment]
Hello Tobias,

Thank you for answering promptly! I was just concerned that even if I adjust the coordinates to 0-based that the read support would still be 1-based. Do you think that if I adjust the positions on the chimeric junction files then the oRNA read support would also be adjusted?

Best, 
Harper

**Comment by harperfauni** [comment]
Is it possible to alter some of the scripts to pull the support reads based on 0-based coordinates?

**Comment by tjakobi** [comment]
Dear @harperfauni,

just so that we are on the same page. You would like to extract the reads that have been mapped to the BSJ per circRNA and would like to have those read mapping coordinates on a 0-based scale?

You shouldn't modify the chimeric.junction.out files of STAR, rather you may modify the DCC results. You can than extract BSJ reads i.e. with bedtools from the BAM files produced by STAR (which also should be 1-based) and when you have all the reads modify the resulting output files.

Does this help?

Cheers,
Tobias
